### ISSUE TITLE
All API responses returning 403 errors

### ISSUE THREAD

**Issue by Peter-Lavigne** [ewen-lbh/subfeed-for-spotify#37]
When I visit https://subfeed-for-spotify.surge.sh/ all Spotify API requests are returning a 403 error. As a result, I am unable to use the app.

The full response from each request is:

> User not registered in the Developer Dashboard

**Comment by ewen-lbh** [comment]
Yes, I actually need to apply for an extended quota. For that, I first need to address all issues that prevent me from applying for this (see https://github.com/ewen-lbh/subfeed-for-spotify/issues?q=is%3Aissue+is%3Aopen+label%3Aspotify-terms).

Until now, you can give me the email address you use for your Spotify account, and I can then add you as a "beta tester" so you can access the app. I've got 18 spots left.
